version: '3'
services:
  app:
    build:
      context: ./app
      args:
        HOST_GID: $HOST_GID
        HOST_UID: $HOST_UID
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
    env_file:
      - .env
    volumes:
      - ./app/public:/var/www/html
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    ports:
      - 3309:3306
    restart: always
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mysql
